# Generated by Django 5.2 on 2025-08-12 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the customer's full name", max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long')])),
                ('phone', models.CharField(help_text="Enter customer's phone number", max_length=15, validators=[django.core.validators.MinLengthValidator(10, 'Phone number must be at least 10 digits')])),
                ('email', models.EmailField(help_text="Enter customer's email address", max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
