# Generated by Django 5.2.5 on 2025-08-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='menu_items/default_food.jpg', help_text='Upload an image for this menu item', upload_to='menu_items/'),
        ),
    ]
